services:
  keycloak:
    container_name: bi_flyer_keycloak
    image: quay.io/keycloak/keycloak:26.4.7
    ports:
      - 9090:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - 'start-dev'

volumes:
  keycloak_data: