spring.application.name=bi-flyer

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bi_flyer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Connection Pool (Optional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000


#KEYCLOAK
keycloak.realm=BI-flyer-automation
keyclock.client.id=client_backend
keycloak.server-url=https://kc-genaiapps.indegene.com/auth/
keyclock.client.secret=7db231fb-782b-409a-a944-37435ade2d92
keycloak.default-role=role-user

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://kc-genaiapps.indegene.com/auth/realms/BI-flyer-automation
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://kc-genaiapps.indegene.com/auth/realms/BI-flyer-automation/protocol/openid-connect/certs